name: "deploy"
on:
# bootstrap이 정상적으로 실행되었을 때 deploy.yml 실행
  workflow_run:
    workflows: ["bootstrap"]
    types: [completed]
    branches: [main]
# 또는 main branch에 paths에 해당하는 폴더 내부가 변경되었을 때 deploy.yml 실행!
  push:
    branches: [main]
    paths:
      - 'terraform/envs/dev/**'

jobs:
  deploy:
    if: |
      github.event_name == 'push' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v5
#################################   
      - name: Wait for S3 bucket
        run: aws s3api wait bucket-exists --bucket project01-tfstate-bucket-mk
#################################
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: terraform init & apply
        working-directory: ./terraform/envs/dev
        run: |
          terraform init
          terraform apply --auto-approve

# 생성된 인벤토리를 S3의 이번 workflow 전용 폴더에 업로드
      - name: Upload Inventory to S3
        run: |
          aws s3 cp ansible/inventories/bootstrap/inventory.yml s3://project01-tfstate-bucket-mk/bootstrap/inventory.yml
          aws s3 cp ansible/inventories/dev/inventory.yml s3://project01-tfstate-bucket-mk/dev/inventory.yml